### ISSUE TITLE
process doesn't close after scraping and DB upload ended

### ISSUE THREAD

**Issue by theDavidBarton** [theDavidBarton/puppeteer-daily-menu-scraper#248]
since #236 - possibbly - we don't close mongoDB connection in the end of the process scrapeDailyMenu.js

it should be investigated what is the issue.

**Comment by theDavidBarton** [comment]
once I've got this after connection was not closed, but this happened with an older version of mongoInsertMany plus a new npm version of mongoDB. so it may be a case of not compatible versions. but anyway, it may help in debugging:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at TLSSocket.<anonymous> (C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\connection\connection.js:321:10)
    at Object.onceWrapper (events.js:277:13)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by theDavidBarton** [comment]
this one is getting higher priority since we are running the main script everday on schedule (GitHub actions scrape.yml)

**debug results:**

checked the processes with [why-is-node-running](https://www.npmjs.com/package/why-is-node-running)

```
# TLSWRAP
(unknown stack trace)

# TLSWRAP
C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\connection\connect.js:266 - socket = tls.connect(parseSslOptions(family,
options));
C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\connection\connect.js:35  - return makeConnection(6, options, (err, ipv6S
ocket) => {
C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\connection\pool.js:571    - connect(self.options, (err, connection) => {
C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\sdam\server.js:153        - this.s.pool.connect();
C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\sdam\topology.js:875      - server.connect();
```
```
# TLSWRAP
C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\connection\connect.js:266 - socket = tls.connect(parseSslOptions(family,
options));
C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\connection\connect.js:37  - makeConnection(4, options, (err, ipv4Socket)
=> {
C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\connection\connect.js:261 - _callback(err, ret);
C:\Users\david.barton\workspace_repos\puppeteer-daily-menu-scraper\node_modules\mongodb\lib\core\connection\connect.js:286 - callback(connectionFailureError(eventName, er
r), eventName);
```

full log: [why-is-node-running_20191121.txt](https://github.com/theDavidBarton/puppeteer-daily-menu-scraper/files/3874870/why-is-node-running_20191121.txt)

**Comment by theDavidBarton** [comment]
they say mongodb 3.3.4 solves the issue: https://github.com/mongodb/node-mongodb-native/releases/tag/v3.3.4
