### ISSUE TITLE
OCR space ErrorMessage condition to be finetuned

### ISSUE THREAD

**Issue by theDavidBarton** [theDavidBarton/puppeteer-daily-menu-scraper#254]
currently https://github.com/theDavidBarton/puppeteer-daily-menu-scraper/blob/master/lib/ocrSpaceApiSimple.js#L30 can throw the following exception in case of `undefined` in response body (most probably due to network error the OCR posts are unsuccesfull):

```
TypeError: Cannot read property 'map' of undefined
    at Request._callback ([...]\puppeteer-daily-menu-scraper\lib\ocrSpaceApiSimple.js:30:49)
    at Request.self.callback ([...]\puppeteer-daily-menu-scraper\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> ([...]\puppeteer-daily-menu-scraper\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> ([...]\puppeteer-daily-menu-scraper\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

in test we should check `undefined` and find a better condition for these cases in the module.
good luck! :duck:

**Comment by theDavidBarton** [comment]
example response if not undefined:
```
{
   "ParsedResults":[
      {
         "TextOverlay":{
            "Lines":[

            ],
            "HasOverlay":false,
            "Message":"Text overlay is not provided as it is not requested"
         },
         "TextOrientation":"0",
         "FileParseExitCode":1,
         "ParsedText":"GAVE AWAY MY BOOK\r\nFREE ON\r\nREACHED TOP OF AMAZON\r\nBESTSELLER\r\n",
         "ErrorMessage":"",
         "ErrorDetails":""
      }
   ],
   "OCRExitCode":1,
   "IsErroredOnProcessing":false,
   "ProcessingTimeInMilliseconds":"388",
   "SearchablePDFURL":"Searchable PDF not generated as it was not requested."
}
```

**Comment by theDavidBarton** [comment]
bump

**Comment by theDavidBarton** [comment]
easy to fix. the issue seems to be the usage of .map is a bad practice here, as we are depending on the quality of the response. if we don't use this unneccesary .map here this issue will be gone.
anyway the parsedResult won't be saved neither after this fix.

**Comment by theDavidBarton** [comment]
during debuging we seems we have this response when the error occurs:
```
"For this API KEY only 3 concurrent connections at the same time allowed. Contact support if you need more."
```
https://forum.ui.vision/t/only-3-concurrent-connections-allowed/3669/8

issue seems to be on OCR space's side, but possibly there can be workarounds.

**Comment by theDavidBarton** [comment]
#269 will close this issue. we can track the fix of the bug on OCR space's side, see the forum link one comment above.
