### ISSUE TITLE
fix dateCatcher bug

### ISSUE THREAD

**Issue by theDavidBarton** [theDavidBarton/puppeteer-daily-menu-scraper#260]
example (on 4th November): 
> HETI MENÜ 11.04. - 11.08.

```
TypeError: Cannot read property '1' of null
   at Object.dateCatcher (...\puppeteer-daily-menu-scraper\lib\dateCatcher.js:51:38)
   at Object.scraper (...\puppeteer-daily-menu-scraper\scrapers\mozsar.js:101:31)
   at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by theDavidBarton** [comment]
fixed by #261
